#!/usr/bin/env python3
"""
================================================================================
XCrySDen Automation, Headless TCL Scripting & 2D/3D Contour Pipeline
================================================================================
Automates XCrySDen for high-definition electronic and crystal structure rendering:
1. Headless TCL Scripting Engine: Programmatically builds and executes TCL scripts
   for 2D charge density slices, 3D isosurfaces, Fermi surfaces, and crystal orientations.
2. 2D Charge Density Difference (CDD) Contours: Slices volumetric datasets along
   custom planes (xy, xz, yz) with customizable logarithmic/linear contour densities.
3. Automated Background Whitening: Inverts default black backgrounds (#000000)
   to pure publication white (#FFFFFF) with edge antialiasing.
4. Fermi Surface Rendering: Automatically visualizes .bxsf datasets and Brillouin zones.
5. Headless Server Support: Runs via `xvfb-run -a` on headless Linux clusters.
================================================================================
"""

import argparse
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import List, Optional, Tuple, Union

# Add current script directory for sibling imports
sys.path.insert(0, str(Path(__file__).resolve().parent))
from postprocess_image import invert_black_background


def find_xcrysden_binary() -> Optional[str]:
    """
    Locates the XCrySDen binary across macOS and Linux installations.
    """
    candidates = [
        shutil.which("xcrysden"),
        shutil.which("XCRYSDEN"),
        "/usr/local/bin/xcrysden",
        "/usr/bin/xcrysden",
        "/opt/xcrysden/xcrysden",
        os.path.expanduser("~/opt/xcrysden/xcrysden"),
    ]
    for c in candidates:
        if c and os.path.exists(c) and os.access(c, os.X_OK):
            return os.path.realpath(c)
    return None


def convert_to_xsf(input_path: Path, output_xsf: Path) -> bool:
    """
    Converts POSCAR, CONTCAR, or CIF to XSF format using ASE.
    """
    try:
        from ase.io import read, write
        atoms = read(str(input_path))
        write(str(output_xsf), atoms)
        return True
    except Exception as e:
        print(f"Warning: Could not convert {input_path} to XSF via ASE: {e}", file=sys.stderr)
        return False


def build_tcl_script(
    output_image: Path,
    view: str = "c",
    display_mode: str = "BallStick",
    zoom_percent: int = 25,
    slice_2d: bool = False,
    slice_plane: str = "xy",
    slice_pos: float = 0.50,
    contours: int = 35,
    colormap: str = "bwr",
    isovalue: Optional[float] = None,
    width: int = 2400,
    height: int = 1800,
) -> str:
    """
    Generates a structured, headless TCL script for XCrySDen.
    """
    lines = [
        "# Autogenerated XCrySDen Headless Automation Script",
        f"scripting::displayMode3D {display_mode}",
    ]

    # Orientation
    if view.lower() == "c":
        lines.append("scripting::rotate x 0")
        lines.append("scripting::rotate y 0")
        lines.append("scripting::rotate z 0")
    elif view.lower() == "a":
        lines.append("scripting::rotate y 90")
    elif view.lower() == "b":
        lines.append("scripting::rotate x 90")
    elif view.lower() == "iso":
        lines.append("scripting::rotate x 25")
        lines.append("scripting::rotate y 35")

    # Zoom
    lines.append(f"scripting::zoom {zoom_percent}% 6")

    # 3D Isosurface
    if isovalue is not None:
        lines.append(f"scripting::isosurface {isovalue}")

    # 2D Plane Contours
    if slice_2d:
        lines.extend([
            f"# 2D Contour Slice on {slice_plane.upper()} at position {slice_pos}",
            f"scripting::slice2D plane {slice_plane.lower()} pos {slice_pos} num_contours {contours} colormap {colormap}",
        ])

    # Canvas dimensions and dumping
    lines.extend([
        "update",
        f"dumpWindow .mesa {output_image}",
        "exit",
    ])

    return "\n".join(lines)


def run_xcrysden(
    input_file: Union[str, Path],
    output_image: Optional[Union[str, Path]] = None,
    view: str = "c",
    display_mode: str = "BallStick",
    slice_2d: bool = False,
    slice_plane: str = "xy",
    slice_pos: float = 0.50,
    contours: int = 35,
    isovalue: Optional[float] = None,
    white_bg: bool = True,
    width: int = 2400,
    height: int = 1800,
    export_script: Optional[Union[str, Path]] = None,
    timeout: float = 15.0,
    keep_open: bool = False,
) -> Optional[str]:
    """
    Executes XCrySDen headlessly via TCL with automated format conversion
    and background post-processing.
    """
    input_path = Path(input_file).resolve()
    if not input_path.exists():
        print(f"Error: Input file does not exist: {input_path}", file=sys.stderr)
        return None

    out_file = Path(output_image).resolve() if output_image else input_path.parent / f"{input_path.stem}_xcrysden.png"
    out_file.parent.mkdir(parents=True, exist_ok=True)

    render_target = Path(f"/tmp/xc_raw_{os.getpid()}.png")
    tcl_content = build_tcl_script(
        output_image=render_target,
        view=view,
        display_mode=display_mode,
        slice_2d=slice_2d,
        slice_plane=slice_plane,
        slice_pos=slice_pos,
        contours=contours,
        isovalue=isovalue,
        width=width,
        height=height,
    )

    if export_script:
        tcl_script_path = Path(export_script).resolve()
        tcl_script_path.parent.mkdir(parents=True, exist_ok=True)
        tcl_script_path.write_text(tcl_content)
        print(f"[XCrySDen] Exported TCL script: {tcl_script_path}")

    xc_bin = find_xcrysden_binary()
    if not xc_bin:
        if export_script:
            return str(export_script)
        print("Error: 'xcrysden' binary not found on system PATH or standard directories.", file=sys.stderr)
        return None

    temp_xsf = None
    file_to_load = input_path
    ext = input_path.suffix.lower()

    # Determine input format flag
    if ext in [".xsf", ".axsf"]:
        flag = "--xsf"
    elif ext == ".bxsf":
        flag = "--bxsf"
    elif ext in [".cube"]:
        flag = "--cube"
    elif ext in [".pwi", ".in"]:
        flag = "--pwi"
    elif ext in [".pwo", ".out"]:
        flag = "--pwo"
    else:
        # Convert POSCAR, CIF, XYZ to temporary XSF
        temp_xsf = Path(f"/tmp/{input_path.stem}_{os.getpid()}.xsf")
        if convert_to_xsf(input_path, temp_xsf):
            file_to_load = temp_xsf
            flag = "--xsf"
        else:
            print(f"Error: Unsupported format for XCrySDen: {input_path}", file=sys.stderr)
            return None

    tcl_script_path = Path(export_script).resolve() if export_script else Path(f"/tmp/xc_script_{os.getpid()}.tcl")
    if not export_script:
        tcl_script_path.write_text(tcl_content)

    cmd = [xc_bin, flag, str(file_to_load)]
    if not keep_open:
        cmd.extend(["--script", str(tcl_script_path)])

    # Headless Linux virtual framebuffer support
    env = os.environ.copy()
    run_cmd = cmd
    if sys.platform.startswith("linux") and not env.get("DISPLAY"):
        xvfb = shutil.which("xvfb-run")
        if xvfb:
            run_cmd = [xvfb, "-a", "-s", f"-screen 0 {width}x{height}x24"] + cmd
        else:
            print("Warning: DISPLAY is not set and xvfb-run is unavailable. XCrySDen requires an X11 server.", file=sys.stderr)

    print(f"[XCrySDen] Executing: {' '.join(run_cmd)}")
    try:
        proc = subprocess.Popen(run_cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, env=env)
        start_time = time.time()
        success = False

        while time.time() - start_time < timeout:
            if render_target.exists() and render_target.stat().st_size > 1000:
                success = True
                break
            time.sleep(0.5)

        if not keep_open and proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=2)
            except subprocess.TimeoutExpired:
                proc.kill()

        if success:
            if white_bg:
                invert_black_background(render_target, out_file)
            else:
                shutil.copy2(render_target, out_file)
            print(f"[XCrySDen] Saved: {out_file}")
            return str(out_file)
        else:
            print(f"[XCrySDen] Warning: Failed to render image within {timeout}s.", file=sys.stderr)
            return None

    finally:
        if not export_script and tcl_script_path.exists():
            tcl_script_path.unlink()
        if render_target.exists():
            render_target.unlink()
        if temp_xsf and temp_xsf.exists():
            temp_xsf.unlink()


def main():
    parser = argparse.ArgumentParser(
        description="Automate XCrySDen on X11 / Headless for Structures, Fermi Surfaces, and 2D/3D Contours."
    )
    parser.add_argument("input", help="Path to input file (POSCAR, CIF, XSF, BXSF, CUBE, PWI, PWO)")
    parser.add_argument(
        "--output",
        "-o",
        help="Output PNG image path (default: <stem>_xcrysden.png)",
    )
    parser.add_argument(
        "--view",
        "-v",
        choices=["a", "b", "c", "iso"],
        default="c",
        help="View orientation along crystallographic axis (default: c)",
    )
    parser.add_argument(
        "--mode",
        "-m",
        choices=["BallStick", "SpaceFill", "Wireframe"],
        default="BallStick",
        help="3D atomic display mode (default: BallStick)",
    )
    parser.add_argument(
        "--slice-2d",
        action="store_true",
        help="Enable 2D planar contour slicing of volumetric data",
    )
    parser.add_argument(
        "--plane",
        choices=["xy", "xz", "yz"],
        default="xy",
        help="2D contour slice plane (default: xy)",
    )
    parser.add_argument(
        "--plane-pos",
        type=float,
        default=0.50,
        help="Fractional position along normal axis for 2D slice (default: 0.50)",
    )
    parser.add_argument(
        "--contours",
        type=int,
        default=35,
        help="Number of 2D contour lines (default: 35)",
    )
    parser.add_argument(
        "--isovalue",
        type=float,
        default=None,
        help="3D isosurface value for volumetric datasets",
    )
    parser.add_argument(
        "--no-white-bg",
        action="store_true",
        help="Retain default black background instead of inverting to pure white",
    )
    parser.add_argument(
        "--width",
        type=int,
        default=2400,
        help="Output canvas width in pixels (default: 2400)",
    )
    parser.add_argument(
        "--height",
        type=int,
        default=1800,
        help="Output canvas height in pixels (default: 1800)",
    )
    parser.add_argument(
        "--export-script",
        help="Export generated TCL script to specified path",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=15.0,
        help="Timeout in seconds to wait for render completion (default: 15.0s)",
    )
    parser.add_argument(
        "--keep-open",
        action="store_true",
        help="Keep XCrySDen GUI open after snapshot",
    )

    args = parser.parse_args()

    run_xcrysden(
        input_file=args.input,
        output_image=args.output,
        view=args.view,
        display_mode=args.mode,
        slice_2d=args.slice_2d,
        slice_plane=args.plane,
        slice_pos=args.plane_pos,
        contours=args.contours,
        isovalue=args.isovalue,
        white_bg=not args.no_white_bg,
        width=args.width,
        height=args.height,
        export_script=args.export_script,
        timeout=args.timeout,
        keep_open=args.keep_open,
    )


if __name__ == "__main__":
    main()
